version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/agent_server
hooks:
  ApplicationStop:
    - location: aws/scripts/application_stop.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: aws/scripts/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: aws/scripts/after_install.sh
      timeout: 1200
      runas: root
  ApplicationStart:
    - location: aws/scripts/application_start.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: aws/scripts/validate_service.sh
      timeout: 300
      runas: root