 const DataBase = [
  'claim,context,text',
  'claim,credentialHash,character varying',
  'claim,credentialType,text',
  'claim,expirationDate,timestamp without time zone',
  'claim,hash,character varying',
  'claim,isObj,boolean',
  'claim,issuanceDate,timestamp without time zone',
  'claim,issuerDid,character varying',
  'claim,subjectDid,character varying',
  'claim,type,character varying',
  'claim,value,text',
  'credential,context,text',
  'credential,expirationDate,timestamp without time zone',
  'credential,hash,character varying',
  'credential,id,character varying',
  'credential,issuanceDate,timestamp without time zone',
  'credential,issuerDid,character varying',
  'credential,raw,text',
  'credential,subjectDid,character varying',
  'credential,type,text',
  'identifier,alias,character varying',
  'identifier,controllerKeyId,character varying',
  'identifier,did,character varying',
  'identifier,provider,character varying',
  'identifier,saveDate,timestamp without time zone',
  'identifier,updateDate,timestamp without time zone',
  'key,identifierDid,character varying',
  'key,kid,character varying',
  'key,kms,character varying',
  'key,meta,text',
  'key,publicKeyHex,character varying',
  'key,type,character varying',
  'message,createdAt,timestamp without time zone',
  'message,data,text',
  'message,expiresAt,timestamp without time zone',
  'message,fromDid,character varying',
  'message,id,character varying',
  'message,metaData,text',
  'message,raw,character varying',
  'message,replyTo,text',
  'message,replyUrl,character varying',
  'message,saveDate,timestamp without time zone',
  'message,threadId,character varying',
  'message,toDid,character varying',
  'message,type,character varying',
  'message,updateDate,timestamp without time zone',
  'message_credentials_credential,credentialHash,character varying',
  'message_credentials_credential,messageId,character varying',
  'message_presentations_presentation,messageId,character varying',
  'message_presentations_presentation,presentationHash,character varying',
  'migrations,id,integer',
  'migrations,name,character varying',
  'migrations,timestamp,bigint',
  'presentation,context,text',
  'presentation,expirationDate,timestamp without time zone',
  'presentation,hash,character varying',
  'presentation,holderDid,character varying',
  'presentation,id,character varying',
  'presentation,issuanceDate,timestamp without time zone',
  'presentation,raw,text',
  'presentation,type,text',
  'presentation_credentials_credential,credentialHash,character varying',
  'presentation_credentials_credential,presentationHash,character varying',
  'presentation_verifier_identifier,identifierDid,character varying',
  'presentation_verifier_identifier,presentationHash,character varying',
  'private-key,alias,character varying',
  'private-key,privateKeyHex,character varying',
  'private-key,type,character varying',
  'service,description,character varying',
  'service,id,character varying',
  'service,identifierDid,character varying',
  'service,serviceEndpoint,character varying',
  'service,type,character varying',
];
module.exports = DataBase;
